#!/bin/sh
#
# chkconfig: 35 99 99
# description: Script to restart Node.js /home/ec2-user/underperforming/server.js
#


. /etc/rc.d/init.d/functions


USER="ec2-user"
NODE_ENV="production"
DAEMON="/usr/local/bin/forever"
ROOT_DIR="/home/ec2-user/underperforming"
SERVER_NAME="underperforming"
SERVER="/usr/local/bin/nodemon --exitcrash"
NODE_BIN="node"
SERVER_FILE="/home/ec2-user/underperforming/server.js"
LOG_FILE="$ROOT_DIR/server.log"
LOCK_FILE="/var/lock/subsys/underperforming"


do_start()
{
    if [ ! -f "$LOCK_FILE" ] ; then
        echo -n $"Starting $SERVER_NAME: "
        runuser -l "$USER" -c "NODE_ENV=$NODE_ENV $DAEMON -a $SERVER $SERVER_FILE>> $LOG_FILE &" && echo_success || echo_failure
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch $LOCK_FILE
else
        echo "$SERVER is locked."
        RETVAL=1
fi
}
do_stop()
{
    echo -n $"Stopping $SERVER_NAME: "
    pid=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}'`
    kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
    pid=`ps -aefw | grep "$SERVER $SERVER_FILE" | grep -v " grep " | awk '{print $2}'`
    kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
    pid=`ps -aefw | grep "$NODE_BIN $SERVER_FILE" | grep -v " grep " | awk '{print $2}'`
    kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}
case "$1" in
    start)
            do_start
            ;;
    stop)
            do_stop
            ;;
    restart)
            do_stop
            do_start
            ;;
    *)
            echo "Usage: $0 {start|stop|restart}"
            RETVAL=1
esac


exit $RETVAL
